name: Benchmark on Windows + Zen3

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [self-hosted, windows]
    timeout-minutes: 12
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Add Ninja to PATH
      shell: powershell
      run: |
        $env:PATH = "C:\tools\ninja;" + $env:PATH
        Write-Host "Ninja added to PATH: $env:PATH"

    - name: Benchmark
      shell: powershell
      working-directory: ${{github.workspace}}
      run: python buildbot\runCI.py -workdir ${{github.workspace}}\labs -runner WinZen3

